### ISSUE TITLE
Questions about his summoning script

### ISSUE THREAD

**Issue by lynxlynxlynx** [Argent77/DjinniCompanion#2]
Hey,

I'm trying to figure out why this mod doesn't fully work yet on gemrb and it brought me to the summoning part. On the face of it it seems to work fine, he appears and talks and follows through the portal. But resummoning doesn't work and it made me wonder whether he's really supposed to be a global actor, saved in the GAM or not (question 1).

Question 2 is related. What is this part of a7afqhlp.baf achieving?
```
  CreateCreature("A7Afaaq", [0.0], 0)
  ActionOverride("A7Afaaq", MakeGlobal())
  ActionOverride("A7Afaaq", DestroySelf())
```
Makes me think we don't understand something about DestroySelf or MakeGlobal if it's working as intended. Is the point here that MakeGlobal doesn't affect the current creature, but creates a copy and then the DestroySelf removes only the map original of the creature? IESDP has a note that repeating a MakeGlobal will create more copies, which could be related.

**Comment by Argent77** [comment]
I somehow missed this topic.

1) The creature is listed as global in the GAM file and behaves like a global creatures when used by the various global-specific script actions. I'm fairly sure it's counted as global by the game engine.

2) This one is more difficult to answer because it's primarily the result of trial and error. Maybe I'm just taking advantage of an engine quirks. My intention was to "disable" the creature by the `DestroySelf()` call (i.e. remove it from the game world). Since the creature is global it should be restored by subsequent `Activate()` calls to the last state. I don't remember exactly why I used `DestroySelf()` in place of `Deactivate()` though. Maybe to have `InMyArea()` calls from the helper creature script return a negative result while the creature is unsummoned. Or maybe to remove him from the party requirement to leave an area.

**Comment by lynxlynxlynx** [comment]
Ok, that helps, thanks.
